steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://laravel-demo-config/.env', '.']
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/backend/api:latest'
      - .
      - '--build-arg'
      - 'GOOGLE_CLOUD_PROJECT=${PROJECT_ID}'
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/backend/api:latest'
    id: Push

  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - '--allow-unauthenticated'
      - 'laravel-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/backend/api:latest'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - managed
      - '--memory'
      - 512Mi
      
    id: Deploy
images:
  - 'gcr.io/$PROJECT_ID/backend/api:latest'
options:
  substitutionOption: ALLOW_LOOSE
